apiVersion: v1
kind: Service
metadata:
  name: blog-zaita-com-nginx-nodeport
  namespace: default
spec:
  type: NodePort
  selector:
    app: blog-zaita-com-nginx
  ports:
    - name: web
      port: 80
      targetPort: 80
      nodePort: 30003